# Generated by Django 3.2.4 on 2021-06-29 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Date_of_Employement', models.DateTimeField()),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField()),
                ('Job', models.CharField(max_length=50)),
            ],
        ),
    ]
