# Generated by Django 3.2.5 on 2021-07-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeMgt', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Date_of_Employement',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(),
        ),
    ]
