# Generated by Django 3.2.5 on 2021-07-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeMgt', '0003_auto_20210727_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Date_of_Employement',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
