# Generated by Django 3.2.6 on 2021-08-23 17:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeMgt', '0005_alter_employee_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
